export interface ToolFAQ {
  question: string
  answer: string
}

export interface Tool {
  id: string
  slug: string
  name: string
  description: string
  longDescription: string
  category: string
  icon: string
  keywords: string[]
  seoTitle: string
  metaDescription: string
  featured: boolean
  popular: boolean
  trending: boolean
  isNew: boolean
  lastUpdated: string
  faqs: ToolFAQ[]
  relatedTools?: string[]
}

// DYNAMIC TOOL ENGINE: Add new tool here and it automatically appears everywhere
// The Tool page at /tools/[slug] will auto-generate SEO, breadcrumbs, related tools
export const tools: Tool[] = [
  {
    id: 'word-counter',
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences and paragraphs instantly',
    longDescription: 'Free online word counter tool to count words, characters, sentences, paragraphs, reading time and speaking time. Perfect for writers, students and professionals.',
    category: 'text',
    icon: '📝',
    keywords: ['word counter', 'character counter', 'word count', 'text counter'],
    seoTitle: 'Free Word Counter - Count Words & Characters Instantly',
    metaDescription: 'Free word counter tool - count words, characters, sentences & paragraphs. Check reading time, speaking time and keyword density instantly.',
    featured: true,
    popular: true,
    trending: true,
    isNew: false,
    lastUpdated: '2025-12-01',
    faqs: [
      { question: 'Is word counter free?', answer: 'Yes, our word counter is 100% free with no limits.' },
      { question: 'Does it count characters with spaces?', answer: 'Yes, we show both counts - with and without spaces.' },
    ],
    relatedTools: ['character-counter', 'case-converter', 'text-to-speech'],
  },
  {
    id: 'character-counter',
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Count characters with and without spaces in real-time',
    longDescription: 'Real-time character counter that counts characters, words, lines and shows character limits for Twitter, Instagram, etc.',
    category: 'text',
    icon: '🔤',
    keywords: ['character counter', 'char count', 'character count'],
    seoTitle: 'Character Counter - Free Online Character Count Tool',
    metaDescription: 'Count characters instantly - real-time counter for tweets, posts, essays. With and without spaces, word count included.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-28',
    faqs: [
      { question: 'What is the character limit?', answer: 'No limit - count unlimited characters for free.' },
    ],
    relatedTools: ['word-counter', 'case-converter'],
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text to uppercase, lowercase, title case and more',
    longDescription: 'Convert text between uppercase, lowercase, title case, sentence case, alternating case and inverse case instantly.',
    category: 'text',
    icon: '🔠',
    keywords: ['case converter', 'uppercase', 'lowercase', 'title case'],
    seoTitle: 'Case Converter - Convert Text Case Free Online',
    metaDescription: 'Free case converter - Convert to UPPERCASE, lowercase, Title Case, Sentence case instantly. Copy results in one click.',
    featured: true,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-25',
    faqs: [
      { question: 'How many case types?', answer: 'We support 6 types: UPPERCASE, lowercase, Title Case, Sentence case, aLtErNaTiNg and InVeRsE.' },
    ],
    relatedTools: ['word-counter', 'slug-generator'],
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate and beautify JSON instantly',
    longDescription: 'Free JSON formatter, validator and beautifier. Format minified JSON, validate syntax, and convert to XML/CSV.',
    category: 'developer',
    icon: '{ }',
    keywords: ['json formatter', 'json validator', 'beautify json', 'json parser'],
    seoTitle: 'JSON Formatter & Validator - Beautify JSON Online Free',
    metaDescription: 'Free JSON formatter - validate, beautify, minify JSON online. Syntax highlighting and error detection included.',
    featured: true,
    popular: true,
    trending: true,
    isNew: false,
    lastUpdated: '2025-12-02',
    faqs: [
      { question: 'Is my JSON data secure?', answer: 'Yes, all processing happens in your browser. No data is sent to server.' },
    ],
    relatedTools: ['base64-encoder', 'base64-decoder', 'url-encoder'],
  },
  {
    id: 'base64-encoder',
    slug: 'base64-encoder',
    name: 'Base64 Encoder',
    description: 'Encode text and files to Base64 instantly',
    longDescription: 'Encode any text to Base64 format instantly. Supports Unicode and file encoding with secure client-side processing.',
    category: 'developer',
    icon: '🔐',
    keywords: ['base64 encoder', 'encode base64', 'text to base64'],
    seoTitle: 'Base64 Encoder - Encode Text to Base64 Free',
    metaDescription: 'Free Base64 encoder - encode text to Base64 instantly. Secure, fast, browser-based encoding.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-20',
    faqs: [{ question: 'What is Base64?', answer: 'Base64 is a binary-to-text encoding scheme that represents binary data in ASCII string format.' }],
    relatedTools: ['base64-decoder', 'url-encoder', 'md5-generator'],
  },
  {
    id: 'base64-decoder',
    slug: 'base64-decoder',
    name: 'Base64 Decoder',
    description: 'Decode Base64 to original text instantly',
    longDescription: 'Decode Base64 encoded strings back to original text. Fast, secure, and works entirely in browser.',
    category: 'developer',
    icon: '🔓',
    keywords: ['base64 decoder', 'decode base64', 'base64 to text'],
    seoTitle: 'Base64 Decoder - Decode Base64 to Text Free Online',
    metaDescription: 'Free Base64 decoder - decode Base64 strings instantly. Secure client-side decoding with error handling.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-20',
    faqs: [{ question: 'Can it decode images?', answer: 'Yes, it can decode Base64 images and files encoded as Base64.' }],
    relatedTools: ['base64-encoder', 'json-formatter'],
  },
  {
    id: 'qr-generator',
    slug: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate custom QR codes for URLs, text, WiFi and more',
    longDescription: 'Free QR code generator for URLs, text, email, phone, WiFi, vCard and more. Download as PNG, SVG with custom colors.',
    category: 'image',
    icon: '⬜',
    keywords: ['qr generator', 'qr code maker', 'create qr code', 'qr code generator free'],
    seoTitle: 'QR Code Generator - Create Custom QR Codes Free',
    metaDescription: 'Free QR code generator - create QR codes for URL, text, WiFi, email. Download PNG/SVG with custom colors.',
    featured: true,
    popular: true,
    trending: true,
    isNew: false,
    lastUpdated: '2025-12-03',
    faqs: [
      { question: 'Are QR codes free forever?', answer: 'Yes, generated QR codes never expire and are free forever.' },
      { question: 'Can I customize colors?', answer: 'Yes, you can customize foreground and background colors.' },
    ],
    relatedTools: ['password-generator', 'color-picker'],
  },
  {
    id: 'password-generator',
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong secure passwords instantly',
    longDescription: 'Generate strong, random passwords with custom length, numbers, symbols, uppercase and lowercase. Secure client-side generation.',
    category: 'converter',
    icon: '🔑',
    keywords: ['password generator', 'strong password', 'random password', 'secure password'],
    seoTitle: 'Strong Password Generator - Create Secure Passwords Free',
    metaDescription: 'Generate strong random passwords - customizable length, numbers, symbols. Secure, no data sent to server.',
    featured: true,
    popular: true,
    trending: true,
    isNew: false,
    lastUpdated: '2025-12-01',
    faqs: [
      { question: 'Are passwords stored?', answer: 'No, passwords are generated locally in your browser and never stored.' },
    ],
    relatedTools: ['qr-generator', 'uuid-generator'],
  },
  {
    id: 'color-picker',
    slug: 'color-picker',
    name: 'Color Picker & Converter',
    description: 'Pick colors and convert between HEX, RGB, HSL formats',
    longDescription: 'Free color picker tool with eye dropper, palette generator, and converter between HEX, RGB, HSL, HSV, CMYK formats.',
    category: 'image',
    icon: '🎨',
    keywords: ['color picker', 'hex color', 'rgb converter', 'color palette'],
    seoTitle: 'Color Picker - HEX RGB HSL Color Converter Free',
    metaDescription: 'Free color picker - pick colors, convert HEX to RGB HSL, generate palettes. Eye dropper tool included.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-18',
    faqs: [{ question: 'Can I pick from image?', answer: 'Yes, upload an image and pick colors from anywhere.' }],
    relatedTools: ['image-compressor', 'qr-generator'],
  },
  {
    id: 'age-calculator',
    slug: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate exact age from birthdate to today',
    longDescription: 'Calculate your exact age in years, months, days, hours, minutes. Also shows next birthday and zodiac sign.',
    category: 'calculator',
    icon: '🎂',
    keywords: ['age calculator', 'calculate age', 'how old am i', 'birthday calculator'],
    seoTitle: 'Age Calculator - Calculate Exact Age Free Online',
    metaDescription: 'Free age calculator - calculate exact age in years months days. Shows birthday countdown and zodiac sign.',
    featured: true,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-15',
    faqs: [{ question: 'How accurate?', answer: 'Calculates exact age down to seconds based on birthdate.' }],
    relatedTools: ['bmi-calculator', 'percentage-calculator'],
  },
  {
    id: 'percentage-calculator',
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages easily - % of number, % increase/decrease',
    longDescription: 'Easy percentage calculator - find X% of Y, what % is X of Y, percentage increase/decrease. Visual and simple.',
    category: 'calculator',
    icon: '％',
    keywords: ['percentage calculator', 'percent calculator', '% calculator'],
    seoTitle: 'Percentage Calculator - Calculate % Free Online',
    metaDescription: 'Free percentage calculator - calculate X% of Y, percentage increase, decrease. Fast and easy to use.',
    featured: true,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-15',
    faqs: [{ question: 'Can calculate discount?', answer: 'Yes, perfect for calculating discounts, tips, and price changes.' }],
    relatedTools: ['discount-calculator', 'loan-calculator'],
  },
  {
    id: 'unit-converter',
    slug: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert length, weight, temperature and more units',
    longDescription: 'All-in-one unit converter for length, weight, temperature, area, volume, speed, time and data storage units.',
    category: 'converter',
    icon: '📏',
    keywords: ['unit converter', 'length converter', 'weight converter', 'temperature converter'],
    seoTitle: 'Unit Converter - Length Weight Temperature Converter Free',
    metaDescription: 'Free unit converter - convert length, weight, temperature, area, volume, speed, data storage instantly.',
    featured: true,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-10',
    faqs: [{ question: 'How many units?', answer: 'Supports 100+ units across 8 categories with instant conversion.' }],
    relatedTools: ['binary-converter', 'percentage-calculator'],
  },
  {
    id: 'ai-prompt-generator',
    slug: 'ai-prompt-generator',
    name: 'AI Prompt Generator',
    description: 'Generate perfect prompts for ChatGPT, Midjourney & more',
    longDescription: 'Generate optimized AI prompts for ChatGPT, Midjourney, DALL-E, Claude. Templates for writing, art, coding, business.',
    category: 'ai',
    icon: '✨',
    keywords: ['ai prompt generator', 'chatgpt prompts', 'midjourney prompts', 'prompt engineering'],
    seoTitle: 'AI Prompt Generator - ChatGPT Midjourney Prompts Free',
    metaDescription: 'Free AI prompt generator - generate perfect prompts for ChatGPT, Midjourney, DALL-E. 50+ templates for all needs.',
    featured: true,
    popular: true,
    trending: true,
    isNew: true,
    lastUpdated: '2025-12-05',
    faqs: [
      { question: 'Which AI models supported?', answer: 'ChatGPT, Midjourney, DALL-E, Stable Diffusion, Claude and more.' },
    ],
    relatedTools: ['keyword-generator', 'youtube-title-generator'],
  },
  {
    id: 'youtube-title-generator',
    slug: 'youtube-title-generator',
    name: 'YouTube Title Generator',
    description: 'Generate viral YouTube titles with AI',
    longDescription: 'Generate catchy, SEO-optimized YouTube titles that get clicks. AI-powered suggestions based on your video topic and keywords.',
    category: 'youtube',
    icon: '🎬',
    keywords: ['youtube title generator', 'video title generator', 'yt title maker'],
    seoTitle: 'YouTube Title Generator - Viral Video Titles Free AI',
    metaDescription: 'Free YouTube title generator - create viral catchy titles that get clicks. AI powered with SEO optimization.',
    featured: true,
    popular: true,
    trending: true,
    isNew: false,
    lastUpdated: '2025-12-04',
    faqs: [{ question: 'How many titles?', answer: 'Generate 10 unique titles per topic instantly.' }],
    relatedTools: ['youtube-description-generator', 'hashtag-generator', 'keyword-generator'],
  },
  {
    id: 'youtube-description-generator',
    slug: 'youtube-description-generator',
    name: 'YouTube Description Generator',
    description: 'Generate SEO YouTube descriptions with timestamps',
    longDescription: 'Generate SEO-optimized YouTube descriptions with timestamps, hashtags, and call-to-actions. Improve ranking and engagement.',
    category: 'youtube',
    icon: '📄',
    keywords: ['youtube description generator', 'yt description maker', 'video description'],
    seoTitle: 'YouTube Description Generator - SEO Descriptions Free',
    metaDescription: 'Free YouTube description generator - SEO descriptions with timestamps, hashtags, keywords. Boost views.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-12-02',
    faqs: [{ question: 'Includes timestamps?', answer: 'Yes, auto-generates timestamps based on your video outline.' }],
    relatedTools: ['youtube-title-generator', 'hashtag-generator'],
  },
  {
    id: 'hashtag-generator',
    slug: 'hashtag-generator',
    name: 'Hashtag Generator',
    description: 'Generate viral hashtags for Instagram, TikTok, YouTube',
    longDescription: 'Generate trending hashtags for Instagram, TikTok, YouTube, Twitter. AI-powered suggestions based on your content.',
    category: 'ai',
    icon: '#️⃣',
    keywords: ['hashtag generator', 'instagram hashtags', 'tiktok hashtags', 'viral hashtags'],
    seoTitle: 'Hashtag Generator - Viral Hashtags for Instagram TikTok Free',
    metaDescription: 'Free hashtag generator - viral hashtags for Instagram, TikTok, YouTube, LinkedIn. AI powered trending tags.',
    featured: true,
    popular: true,
    trending: true,
    isNew: false,
    lastUpdated: '2025-12-01',
    faqs: [{ question: 'Which platforms?', answer: 'Supports Instagram, TikTok, YouTube, Twitter, LinkedIn, Facebook.' }],
    relatedTools: ['keyword-generator', 'youtube-title-generator'],
  },
  {
    id: 'keyword-generator',
    slug: 'keyword-generator',
    name: 'Keyword Generator',
    description: 'Generate SEO keywords for YouTube and websites',
    longDescription: 'Generate high-ranking SEO keywords for YouTube videos, blogs, and websites. Includes search volume and competition ideas.',
    category: 'ai',
    icon: '🔍',
    keywords: ['keyword generator', 'seo keywords', 'youtube keywords', 'keyword tool'],
    seoTitle: 'Keyword Generator - Free SEO Keywords Tool',
    metaDescription: 'Free keyword generator - SEO keywords for YouTube, blogs, websites. Find high ranking low competition keywords.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-30',
    faqs: [{ question: 'Free to use?', answer: 'Yes, generate unlimited keywords for free without signup.' }],
    relatedTools: ['hashtag-generator', 'ai-prompt-generator'],
  },
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress images without losing quality',
    longDescription: 'Compress JPG, PNG, WebP images to reduce file size up to 90% without visible quality loss. Batch compression supported.',
    category: 'image',
    icon: '🗜️',
    keywords: ['image compressor', 'compress image', 'reduce image size', 'jpg compressor'],
    seoTitle: 'Image Compressor - Compress Images Without Quality Loss Free',
    metaDescription: 'Free image compressor - compress JPG PNG WebP up to 90% smaller. No quality loss, batch compression, secure.',
    featured: true,
    popular: true,
    trending: true,
    isNew: false,
    lastUpdated: '2025-12-03',
    faqs: [
      { question: 'Quality loss?', answer: 'Smart compression reduces size 60-90% with almost no visible quality loss.' },
      { question: 'Max file size?', answer: 'Up to 10MB per image, unlimited images.' },
    ],
    relatedTools: ['image-resizer', 'image-to-base64'],
  },
  {
    id: 'image-resizer',
    slug: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images to any dimensions instantly',
    longDescription: 'Resize images to exact width height, or percentage. Maintain aspect ratio, choose output format JPG PNG WebP.',
    category: 'image',
    icon: '↔️',
    keywords: ['image resizer', 'resize image', 'change image size', 'photo resizer'],
    seoTitle: 'Image Resizer - Resize Images to Any Size Free',
    metaDescription: 'Free image resizer - resize JPG PNG to any dimensions. Maintain quality, aspect ratio, batch resize.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-22',
    faqs: [{ question: 'Maintain aspect ratio?', answer: 'Yes, option to lock aspect ratio while resizing.' }],
    relatedTools: ['image-compressor', 'color-picker'],
  },
  {
    id: 'image-to-base64',
    slug: 'image-to-base64',
    name: 'Image to Base64',
    description: 'Convert images to Base64 string instantly',
    longDescription: 'Convert JPG, PNG, SVG, WebP images to Base64 data URI for embedding in HTML, CSS, JSON. Preview included.',
    category: 'image',
    icon: '🖼️',
    keywords: ['image to base64', 'jpg to base64', 'png to base64', 'base64 image'],
    seoTitle: 'Image to Base64 Converter - Convert Images Free Online',
    metaDescription: 'Convert images to Base64 free - JPG PNG to Base64 data URI. For HTML CSS embedding, instant conversion.',
    featured: false,
    popular: false,
    trending: false,
    isNew: true,
    lastUpdated: '2025-12-01',
    faqs: [{ question: 'What is Base64 image?', answer: 'Base64 image is text representation of image that can be embedded directly in code.' }],
    relatedTools: ['base64-encoder', 'image-compressor'],
  },
  {
    id: 'text-to-speech',
    slug: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert text to natural speech audio free',
    longDescription: 'Free text to speech converter with natural voices. Supports 50+ languages, download audio as MP3, adjustable speed.',
    category: 'ai',
    icon: '🔊',
    keywords: ['text to speech', 'tts', 'text to audio', 'voice generator'],
    seoTitle: 'Text to Speech Free - Convert Text to Audio MP3',
    metaDescription: 'Free text to speech - convert text to natural speech, 50+ voices, download MP3. No signup required.',
    featured: true,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-28',
    faqs: [{ question: 'Download audio?', answer: 'Yes, you can download converted speech as audio file where supported.' }],
    relatedTools: ['word-counter', 'ai-prompt-generator'],
  },
  {
    id: 'lorem-ipsum-generator',
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for designs',
    longDescription: 'Generate Lorem Ipsum placeholder text for web design, mockups, print layouts. Custom paragraphs, words, bytes.',
    category: 'text',
    icon: '📃',
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text generator', 'lipsum'],
    seoTitle: 'Lorem Ipsum Generator - Placeholder Text Free',
    metaDescription: 'Free Lorem Ipsum generator - placeholder text for design. Custom paragraphs words bytes generation.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-18',
    faqs: [{ question: 'What is Lorem Ipsum?', answer: 'Lorem Ipsum is dummy text used in printing and web design as placeholder.' }],
    relatedTools: ['word-counter', 'slug-generator'],
  },
  {
    id: 'slug-generator',
    slug: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate SEO-friendly URL slugs from text',
    longDescription: 'Generate clean SEO-friendly URL slugs from titles. Removes special characters, lowercases, hyphenates for best SEO.',
    category: 'text',
    icon: '🔗',
    keywords: ['slug generator', 'url slug', 'seo slug', 'permalink generator'],
    seoTitle: 'Slug Generator - SEO URL Slug Generator Free',
    metaDescription: 'Free slug generator - convert titles to SEO friendly URL slugs. Clean URLs for better ranking.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-16',
    faqs: [{ question: 'What is a slug?', answer: 'Slug is the URL-friendly version of title used in website URLs for SEO.' }],
    relatedTools: ['case-converter', 'word-counter'],
  },
  {
    id: 'url-encoder',
    slug: 'url-encoder',
    name: 'URL Encoder & Decoder',
    description: 'Encode and decode URLs instantly',
    longDescription: 'Encode and decode URLs to make them safe for transmission. Encode special characters, decode encoded URLs.',
    category: 'developer',
    icon: '🌐',
    keywords: ['url encoder', 'url decoder', 'encode url', 'decode url'],
    seoTitle: 'URL Encoder Decoder - Encode Decode URLs Free',
    metaDescription: 'Free URL encoder decoder - encode URLs safe for transmission, decode encoded URLs instantly.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-15',
    faqs: [{ question: 'Why encode URL?', answer: 'URLs with special characters need encoding to work correctly in browsers and servers.' }],
    relatedTools: ['base64-encoder', 'json-formatter'],
  },
  {
    id: 'md5-generator',
    slug: 'md5-generator',
    name: 'MD5 Hash Generator',
    description: 'Generate MD5 hash from text instantly',
    longDescription: 'Generate MD5 hash, SHA1, SHA256, SHA512 hashes from any text. Secure client-side hashing.',
    category: 'developer',
    icon: '🔒',
    keywords: ['md5 generator', 'hash generator', 'sha256', 'md5 hash'],
    seoTitle: 'MD5 SHA Hash Generator - Generate Hashes Free Online',
    metaDescription: 'Free hash generator - MD5 SHA1 SHA256 SHA512 hashes from text. Secure browser-side generation.',
    featured: false,
    popular: false,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-14',
    faqs: [{ question: 'Is MD5 secure?', answer: 'MD5 is good for checksums but not for passwords. Use SHA256 for security.' }],
    relatedTools: ['base64-encoder', 'password-generator'],
  },
  {
    id: 'bmi-calculator',
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index instantly',
    longDescription: 'Calculate BMI (Body Mass Index) from height and weight. Shows BMI category, healthy weight range, health tips.',
    category: 'calculator',
    icon: '⚖️',
    keywords: ['bmi calculator', 'body mass index', 'bmi chart', 'calculate bmi'],
    seoTitle: 'BMI Calculator - Calculate Body Mass Index Free',
    metaDescription: 'Free BMI calculator - calculate Body Mass Index from height weight. Shows healthy range and tips.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-12',
    faqs: [{ question: 'What is healthy BMI?', answer: 'Healthy BMI range is 18.5 to 24.9 according to WHO.' }],
    relatedTools: ['age-calculator', 'percentage-calculator'],
  },
  {
    id: 'loan-calculator',
    slug: 'loan-calculator',
    name: 'Loan Calculator',
    description: 'Calculate loan EMI, interest and payments',
    longDescription: 'Calculate loan EMI, total interest, total payment, amortization schedule. For home loan, car loan, personal loan.',
    category: 'calculator',
    icon: '🏦',
    keywords: ['loan calculator', 'emi calculator', 'mortgage calculator', 'interest calculator'],
    seoTitle: 'Loan EMI Calculator - Calculate EMI Interest Free',
    metaDescription: 'Free loan calculator - calculate EMI, total interest, amortization. For home, car, personal loans.',
    featured: true,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-10',
    faqs: [{ question: 'What is EMI?', answer: 'EMI is Equated Monthly Installment you pay to repay loan.' }],
    relatedTools: ['percentage-calculator', 'discount-calculator'],
  },
  {
    id: 'binary-converter',
    slug: 'binary-converter',
    name: 'Binary Converter',
    description: 'Convert text to binary and binary to text',
    longDescription: 'Convert text to binary code and binary to text. Supports ASCII, Unicode, decimal, hex, octal conversions.',
    category: 'converter',
    icon: '0️⃣',
    keywords: ['binary converter', 'text to binary', 'binary to text', 'binary translator'],
    seoTitle: 'Binary Converter - Text to Binary Converter Free',
    metaDescription: 'Free binary converter - convert text to binary, binary to text, decimal hex. Instant conversion.',
    featured: false,
    popular: false,
    trending: false,
    isNew: true,
    lastUpdated: '2025-12-01',
    faqs: [{ question: 'What is binary?', answer: 'Binary is base-2 number system using 0 and 1 that computers use.' }],
    relatedTools: ['unit-converter', 'url-encoder'],
  },
  {
    id: 'discount-calculator',
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    description: 'Calculate discount price and savings',
    longDescription: 'Calculate discounted price, savings amount, and original price. Perfect for shopping and sales calculations.',
    category: 'calculator',
    icon: '🏷️',
    keywords: ['discount calculator', 'sale calculator', 'price calculator', 'savings calculator'],
    seoTitle: 'Discount Calculator - Calculate Sale Price Free',
    metaDescription: 'Free discount calculator - calculate sale price, savings, discount percentage. Perfect for shopping.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-08',
    faqs: [{ question: 'Calculate original price?', answer: 'Yes, enter discounted price and discount % to get original price.' }],
    relatedTools: ['percentage-calculator', 'loan-calculator'],
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs/GUIDs instantly',
    longDescription: 'Generate random UUID v1 and v4, GUIDs in bulk. Copy single or multiple UUIDs, customize format.',
    category: 'developer',
    icon: '🆔',
    keywords: ['uuid generator', 'guid generator', 'uuid v4', 'random uuid'],
    seoTitle: 'UUID Generator - Generate Random UUID GUID Free',
    metaDescription: 'Free UUID generator - generate random UUID v4 GUIDs in bulk. Custom format, copy instantly.',
    featured: false,
    popular: false,
    trending: false,
    isNew: true,
    lastUpdated: '2025-12-02',
    faqs: [{ question: 'What is UUID?', answer: 'UUID is 128-bit unique identifier used in software development.' }],
    relatedTools: ['password-generator', 'md5-generator'],
  },
  {
    id: 'meta-tag-generator',
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO meta tags for websites',
    longDescription: 'Generate SEO meta tags - title, description, keywords, Open Graph, Twitter Card, robots for better SEO ranking.',
    category: 'developer',
    icon: '🏷️',
    keywords: ['meta tag generator', 'seo meta tags', 'open graph generator', 'twitter card'],
    seoTitle: 'Meta Tag Generator - SEO Meta Tags Generator Free',
    metaDescription: 'Free meta tag generator - generate SEO meta tags, Open Graph, Twitter cards for better ranking.',
    featured: false,
    popular: true,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-25',
    faqs: [{ question: 'What are meta tags?', answer: 'Meta tags are HTML tags that provide info about webpage to search engines.' }],
    relatedTools: ['slug-generator', 'keyword-generator'],
  },
  {
    id: 'pdf-to-text',
    slug: 'pdf-to-text',
    name: 'PDF to Text Extractor',
    description: 'Extract text from PDF files online free',
    longDescription: 'Extract text from PDF files instantly. Works with scanned PDFs (OCR), multiple pages, keep formatting.',
    category: 'pdf',
    icon: '📑',
    keywords: ['pdf to text', 'extract text from pdf', 'pdf text extractor', 'pdf ocr'],
    seoTitle: 'PDF to Text - Extract Text from PDF Free Online',
    metaDescription: 'Extract text from PDF free - PDF to text converter with OCR. Multiple pages, keep formatting.',
    featured: true,
    popular: false,
    trending: false,
    isNew: true,
    lastUpdated: '2025-12-05',
    faqs: [{ question: 'Supports scanned PDF?', answer: 'Yes, OCR support extracts text from scanned PDFs.' }],
    relatedTools: ['word-counter', 'json-formatter'],
  },
  {
    id: 'hex-to-rgb',
    slug: 'hex-to-rgb',
    name: 'HEX to RGB Converter',
    description: 'Convert HEX colors to RGB and vice versa',
    longDescription: 'Convert HEX color codes to RGB, RGB to HEX, HSL. Preview colors, generate shades and tints.',
    category: 'converter',
    icon: '🌈',
    keywords: ['hex to rgb', 'rgb to hex', 'color converter', 'hex color'],
    seoTitle: 'HEX to RGB Converter - Color Converter Free Online',
    metaDescription: 'Free HEX to RGB converter - convert HEX to RGB HSL, preview colors, generate shades.',
    featured: false,
    popular: false,
    trending: false,
    isNew: false,
    lastUpdated: '2025-11-20',
    faqs: [{ question: 'What is HEX?', answer: 'HEX is hexadecimal color code used in web design like #FF5733.' }],
    relatedTools: ['color-picker', 'binary-converter'],
  },
]

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find(t => t.slug === slug)
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter(t => t.category === category)
}

export function getFeaturedTools(): Tool[] {
  return tools.filter(t => t.featured)
}

export function getPopularTools(): Tool[] {
  return tools.filter(t => t.popular)
}

export function getTrendingTools(): Tool[] {
  return tools.filter(t => t.trending)
}

export function getNewTools(): Tool[] {
  return tools.filter(t => t.isNew)
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase()
  return tools.filter(t => 
    t.name.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.keywords.some(k => k.toLowerCase().includes(q)) ||
    t.category.toLowerCase().includes(q)
  )
}

export function getRelatedTools(slug: string): Tool[] {
  const tool = getToolBySlug(slug)
  if (!tool || !tool.relatedTools) {
    // Return random tools from same category
    const sameCat = getToolsByCategory(tool?.category || 'text').filter(t => t.slug !== slug)
    return sameCat.slice(0, 3)
  }
  return tool.relatedTools.map(s => getToolBySlug(s)).filter(Boolean) as Tool[]
}
